# Generated by Django 4.0.5 on 2022-07-08 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='descuento',
            fields=[
                ('idDescuento', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreDescuento', models.CharField(max_length=20)),
                ('cantidadDescuento', models.IntegerField()),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=20)),
                ('stockProducto', models.IntegerField()),
                ('precioProducto', models.IntegerField()),
                ('imagenProducto', models.ImageField(null=True, upload_to='productos')),
                ('descuento_aplicado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.descuento')),
            ],
        ),
    ]
